name: NSG

on: 
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master 
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: CU-CommunityApps/ct-az-blueprints
        token: ${{ secrets.ACCESS_TOKEN }}
